@startuml

actor Customer

participant "CustomerService" as CustomerService
participant "Order" as Order
participant "Payment" as Payment
participant "Customer Screen" as CustomerScreen

actor Administrador
actor Kitchen

Customer -> CustomerService: Registrar no sistema
Customer -> CustomerService: Realizar login no sistema
Customer -> CustomerService: Entrar como guest no sistema
Customer -> Order: Adicionar itens ao order
Customer -> Order: Remover itens do order
Customer -> Order: Confirmar order
Customer -> Order: Calcular valor total

Order -> Order: Gerar order
Order -> Order: Calcular valor total
Order -> Payment: Realizar payment

Payment -> Order: Realizar payment via QRCode
Payment --> Customer: Verificar payment

Order -> Kitchen: Enviar order para preparação

Administrador -> Order: Atualizar status do order

Order -> Customer: Exibir status do order

Kitchen -> Kitchen: Preparar order

Kitchen -> Customer: Notificar que o order está pronto para retirada
Customer -> Kitchen: Retirar order

Kitchen -> Order: Atualizar status do order para finalizado

Administrador -> CustomerService: Gerenciar clientes
Administrador -> Product: Gerenciar produtos e categorias
Administrador -> Order: Acompanhar pedidos em andamento
Administrador -> Order: Gerenciar informações

@enduml