version: '3'
services:
  postgres:
    container_name: postgres
    image: mauricio1998/tech-db
    volumes:
      - ../build/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "fiap_tech_challenge"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_USER: "postgres"
    networks:
      - tech-challenge-nw

  tech-challenge:
    image: tech-challenge
    ports:
      - "3001:3001"
      - "3002:3002"
    networks:
      - tech-challenge-nw

  tech-challenge-auth:
    image: auth
    ports:
      - "3003:3003"
    networks:
      - tech-challenge-nw

networks:
  tech-challenge-nw:
    driver: bridge