version: '3'
services:

  postgres:
    image: postgres:latest
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=1234
    networks:
      - tech-challenge-nw

  tech-challenge-fase-1:
    image: tech-challenge
    ports:
      - 3001:3001
    networks:
      - tech-challenge-nw

networks:
  tech-challenge-nw:
    driver: bridge