apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge
  labels:
    app: tech-challenge-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tech-challenge-app
  template:
    metadata:
      labels:
        app: tech-challenge-app
    spec:
      containers:
        - name: tech-challenge
          image: mauricio1998/tech-challenge
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: app-config          
          ports:
            - containerPort: 3001
          volumeMounts:
            - name: configmap-tech-challenge
              subPath: config.yaml
              mountPath: /app/config.yaml
      volumes:
        - name: configmap-tech-challenge
          configMap:
            name: "tech-challenge-cm"