apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: alb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  name: tech-challenge-app
  labels:
    app: tech-challenge-app
spec:
  selector:
    app: tech-challenge-app
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: LoadBalancer