apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tech-challenge
  name: tech-challenge-deploy
  namespace: fiap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tech-challenge
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tech-challenge
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: tech-challenge-cm
        - secretRef:
            name: tech-challenge-secret
        image: tech-challenge
        name: tech-challenge
        ports:
        - containerPort: 9112
          name: grpc
          protocol: TCP
        - containerPort: 7777
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: 50m
            memory: 150Mi
          requests:
            cpu: 30m
            memory: 100Mi
        volumeMounts:
        - mountPath: /var/gcp/
          name: gcp-key
        - mountPath: /app/config/
          name: taxes-csv
      volumes:
      - name: gcp-key
        secret:
          defaultMode: 420
          secretName: taxes
      - configMap:
          defaultMode: 420
          items:
          - key: taxes.csv
            path: taxes.csv
          name: taxes-csv
        name: taxes-csv