apiVersion: v1
kind: Secret
metadata:
  name: app-config
  namespace: fiap
type: Opaque
data:
  APP_TOKEN_KEY: "dnVJWGFPSzRPcEpXQTl5U1gxVVRwSVdzaFhQcFA2bmVHS0dBNzI0RmF1WQ=="
  APP_DB_CONNECTION_STRING: "aG9zdD1wb3N0Z3Jlcy1zZXJ2aWNlLmZpYXAuc3ZjLmNsdXN0ZXIubG9jYWwgcG9ydD01NDMyIGRibmFtZT1maWFwX3RlY2hfY2hhbGxlbmdlIHVzZXI9cG9zdGdyZXMgcGFzc3dvcmQ9MTIzNCBzc2xtb2RlPWRpc2FibGU="