apiVersion: v1
kind: Service
metadata:
  labels:
    app: tech-challenge
  name: tech-challenge-svc
  namespace: tech-challenge
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 8080
      targetPort: 3001
  selector:
    app: tech-challenge